/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void chasesMethod() {
        System.out.println("this is a chases method");
    }
     public static void danishsMethod() {
        System.out.println("this is a danishs method");
     }
     public static void brycesMethod() {
        System.out.println("this is a bryces method");
     }
     public static void asimsMethod() {
        System.out.println("this is a asims method");

        AsimaFeatures.runAsimaDemo();
    }

     public static void leifsMethod() {
        System.out.println("this is a leifs method");
        
    }
    public static void main(String[] args) {
      //  System.out.println(new App().getGreeting());
      System.out.println("this is a main method");
      chasesMethod();
      danishsMethod();
      brycesMethod();
      asimsMethod();
      leifsMethod();
    }
}
