/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.*;
import java.util.stream.Collectors;

public class App {

    public String getGreeting() {
        return "\n\n=========================\nMy new, better, greeting!\n=========================\n\n";
    }

    // Event class - now public & static (testable)
    public static class Event {
        public String name;
        public String tag;
        public String color;

        public Event(String name, String tag, String color) {
            this.name = name;
            this.tag = tag;
            this.color = color;
        }

        public void display() {
            System.out.println(color + name + " [" + tag + "]" + "\u001B[0m");
        }
    }

    // Helper method for testing (pure logic, no printing)
    public static List<Event> filterEventsByTag(List<Event> events, String filterTag) {
        if (filterTag == null || filterTag.isEmpty()) return List.of();
        return events.stream()
                .filter(e -> e.tag.equalsIgnoreCase(filterTag))
                .collect(Collectors.toList());
    }

    // Chase's method – now uses helper method
    public static void chasesMethod() {
        System.out.println("\n=== Chase's Method: Event Color Coding & Tag Filtering ===");

        List<Event> events = List.of(
            new Event("Math Homework", "Homework", "\u001B[34m"),
            new Event("Science Homework", "Homework", "\u001B[34m"),
            new Event("Basketball Practice", "Sports", "\u001B[32m"),
            new Event("Dentist Appointment", "Health", "\u001B[31m")
        );

        String filterTag = "Homework";
        System.out.println("Filtering by tag: " + filterTag + "\n");

        List<Event> filtered = filterEventsByTag(events, filterTag);
        for (Event e : filtered) {
            e.display();
        }

        System.out.println("=== End of Chase's Method ===\n");
    }

    // Danish's method
    public static void danishsMethod() {
        System.out.println("this is a danishs method");
    }

    // Bryce's method
    public static void brycesMethod() {
        System.out.println("this is a bryces method");
    }

    // Asim's method
    public static void asimsMethod() {
        System.out.println("this is an asims method");
    }

    // Leif's method
    public static void leifsMethod() {
        System.out.println("this is a leifs method");
    }

    // Main method
    public static void main(String[] args) {
        System.out.println("this is the main method");

        // Call each team member's method
        chasesMethod();
        danishsMethod();
        brycesMethod();
        asimsMethod();
        leifsMethod();
    }
}
